### ISSUE TITLE
react native client install error.

### ISSUE THREAD

**Issue by suijunqiang** [srtucker22/chatty#32]
react native client install error as blow and install progress will be suspended here:
npm ERR! Unexpected end of JSON input while parsing near '...tro/download/metro-0.'

**reproduce:**
cd client
npm install
you will get the error, any my env as blow:
node: v11.2.0
rn: react-native-cli: 2.0.1

**Comment by srtucker22** [comment]
I just ran a clean clone and install of chatty today with the following:
node v11.3.0
npm v6.5.0
rn cli v2.0.1

so i don't think the issue is specific to the project

a quick search on StackOverflow suggests:
clear the cache for NPM npm cache clean.
delete node_modules
reinstall your dependencies using npm install.

Let me know if that helps

**Comment by suijunqiang** [comment]
Opooos!
The issue has been fixed by using "yarn install"
BTW the ios code of react native could be compiling well on the xcode 9 not 10.

Thanks @srtucker22 any way.
