### ISSUE TITLE
[Network error] Android 

### ISSUE THREAD

**Issue by durdevic** [srtucker22/chatty#33]
Hey man, awesome thing you made, really liked the tutorial 👌

Quick question, I'm trying to get the app running on Android and getting "**Network error: Network request failed**". Does it happen to you as well, and if yes do you maybe have an idea how it might be resolved? On iOS it's working.

I'm trying to figure it out, if I find solution I'll provide PR. 

Cheers!

**Comment by srtucker22** [comment]
Thanks, @durdevic!

I’ve focussed this tutorial for development in iOS, so there is a strong possibility that things won’t work in Android. I’ve been planning on stepping through the tutorial in Android to see where things might break, but haven't had the time.

That said, regarding your issue, I think the problem is that unlike the iOS Simulator, Android Studio uses an actual emulator, so it doesn’t have a reference to localhost on your machine. To fix your issue, simply change the `httpLink` uri to the following:

```js
//  client/src/app.js
const URL = 'http://10.0.2.2:8080'; // set your comp's url here

...

const httpLink = createHttpLink({ uri: `http://${URL}` });
const link = ApolloLink.from([
  reduxLink,
  errorLink,
  httpLink,
]);

export const client = new ApolloClient({
  link,
  cache,
});
```

You can also change this uri to the IP of your machine e.g. `http://192.168.1.1:8080`

Let me know if that solves it.

**Comment by durdevic** [comment]
@srtucker22 You, brilliant! 💪🎸
